From: Your guardian angel
To: Lago
Subject: Congratulations!
Date: Sun May 21, 2023 13:05
-------------
Your character has been deemed ready to take on the world without my protection, meaning that you may now raise your sword against other players if you so desire.  It is with a heavy heart that I take my leave of you, but I trust that you will do fine without me.

You also have many other rights and responsibilities available to you.  You can now join a guild with other friends.  Guilds are a good way to gain protection from those that would do you harm.  Joining a good guild will make the difference between merely surviving or thriving in the world.  Guilds can also get into wars with other guilds, so be careful that you don't make too many enemies.

You can also participate in the politics of Meridian.  In the royal city of Barloque there is a clerk named Caramo which handles the election of the position of Justicar.  The Justicar pardons those that have been flagged as outlaws and murderers.  Unless you wish to see such villians get pardons, it is important to be active in voting.

I must warn you that engaging in lethal combat against other players may soil your good name.  If you strike an innocent, or cast a spell which harms him, you may be branded an outlaw, an onus which only fades upon your death.  If you slay an innocent in cold blood, you will be blacklisted as a murderer, and this is a weight upon your soul which does not easily depart.  This puts you at risk:  since murderers and outlaws are not innocents, one may attack them without being named a murderer or an outlaw.

Also note that assisting an outlaw or murder by casting helpful spells upon them will brand you an outlaw in the eyes of society.  You must choose your friends and your enemies well!

If you do not wish to engage in the unsavory practice of attacking innocents or assisting the unlawful, it is heartily recommended that you do not enable attacking innocents in your game preferences.  This is also called your "safety" since it keeps you safe from being outcast as an unlawful outlaw or murderer.  While your safety is on, you are not permitted to either attack innocents or cast spells that are hostile to them.  This can be crucial when one stray sword blow can make you an outlaw.  However, rest assured that you will always be permitted to strike outlaws and murderers, since it is crucial that you always have the option of defending yourself from their treacherous ways.

Your safety is currently on, meaning you cannot cast hostile spells or attack innocent players.

Finally, some last bits of advice as I depart.  Do not dispair if you are sent to the underworld by some monster or even another player.  Death is part of the cycle, and learning to recover from death is important.  Put some items away in the vault in Barloque for times when you find yourself killed and unable to get items from your corpse.  Also, ask politely for assistance and you will often find someone willing to lend a helping hand.  Make some friends and you will find that nothing is truly beyond your reach.

Have fun in Meridian!

  -- Your guardian angel