From: Baron Springer of Cor Noth Township
To: Lago
Subject: Invitation to visit the Royal Court
Date: Mon May 29, 2023 06:56
-------------
Oh, most worthy adventurer.  Tales of your exploits have been oft told here at the Court, and recently, the Meridian Council itself declared you to possess considerable promise. Perhaps someday you will be given the honor of studying and guarding one of the Five Tokens.

The Council serves our fair land by using their acquired knowledge to benefit daily life. For the most part, they are honest and impartial in their decisions - guided by the Priestess of Shal'ille. However, Duke Akardius and Princess Kateriina and their factions of followers try to sway the Council down differing paths:

Duke Akardius wishes for more of the Council's energies to be used for the benefit of commerce and the study of lore, while the Princess seeks their aid in advancing knowledge of magic. Both believe their path is the way to reduce the plague of monsters which terrify the land these days.

There are also boorish tales of a third faction of rebels.  They are dissatisfied with the current political climate and seek to bring their leader to rule our lands.  I do not know much about these rebels, nor do I care to learn anything.  You are on your own if you wish to learn about them.

Should you desire to join any of these factions, seek the Liege. As a faction member, you can help to influence the Council yourself, and share in the benefits of belonging to the party in power. You will need to demonstrate fealty to your Liege on a regular basis to keep your name on the rolls. Even if you join neither faction, you will still be influenced by the Council's decisions - as are all.

Fair partings, and perhaps we will someday meet at the court.

----Baron of Cor Noth Township, Gerah Springer.