From: Your guardian angel
To: Lago
Subject: Penalties for logging off in an unsafe area
Date: Thu Jun 01, 2023 22:44
-------------
You have suffered some penalties for logging off in an unsafe area:
You lost 0 items, 0 spell points, and 0 skill points.

In the future, it would be wise to log off in a safe area such as an inn, an adventurer's hall, or the interior of your guild's hall.

Abandoning your body in an unsafe area weakens it, which may cause you to suffer some of the effects of death: you could lose proficiency in spells and skills, as well as loosening your grip on items in your possession.  You have a 10 minute grace period after logoff before penalties are incurred, so if you lose your connection involuntarily, simply reconnect within 10 minutes and your character will be fine.  Every time you log off unsafely in a short period of time, your body becomes progressively weaker and as such will suffer more from being abandoned.  The first time you logoff unsafely, you will suffer little or no penalties, but once you have performed enough unsafe logoffs, the damage to your body will be comparable to the losses incurred when your character dies.  This penalty escalation recedes over time, so if you don't log off unsafely too frequently, your character should suffer only mild if any penalties.

I recommend you do not use this as a tactic to avoid danger, since it could work against you should your connection to the Meridian become too unstable soon after.

  -- Your guardian angel